# Generated by Django 4.1.3 on 2022-11-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='gallery_display_name',
            field=models.CharField(default=models.CharField(max_length=20), max_length=20),
        ),
    ]
