# Generated by Django 4.1.3 on 2022-11-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_rename_gallery_display_name_gallery_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='gallery_name',
            new_name='name',
        ),
    ]
